# Generated by Django 3.2.16 on 2023-02-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0006_alter_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Цех/отдел', max_length=30, verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mark', models.CharField(blank=True, help_text='Гос.рег.знак', max_length=10, null=True, verbose_name='ГРЗ')),
                ('brand', models.CharField(blank=True, help_text='Марка транспортного средства', max_length=50, null=True, verbose_name='Марка ТС')),
                ('route_movement', models.CharField(help_text='Маршрут движения', max_length=100, verbose_name='Маршрут движения')),
                ('time_delivery_car_on_base', models.CharField(blank=True, help_text='Время подачи на БПО', max_length=100, null=True, verbose_name='Время подачи на БПО')),
                ('time_delivery_car_on_borehole', models.CharField(blank=True, help_text='Время подачи на скважину', max_length=100, null=True, verbose_name='Время подачи на скважину')),
                ('quantity_hours', models.IntegerField(blank=True, help_text='Количество часов', null=True, verbose_name='Количество часов')),
                ('note', models.CharField(blank=True, help_text='Примечание', max_length=300, null=True, verbose_name='Примечание')),
                ('type_car', models.ForeignKey(help_text='Тип транспортного средства', on_delete=django.db.models.deletion.CASCADE, related_name='type', to='cars.typecar', verbose_name='Тип ТС')),
            ],
        ),
    ]
