# Generated by Django 3.2.16 on 2023-09-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_movement', models.CharField(help_text='Маршрут движения', max_length=100, verbose_name='Маршрут движения')),
                ('time_delivery_car_on_base', models.CharField(blank=True, help_text='Время подачи на БПО', max_length=100, null=True, verbose_name='Время подачи на БПО')),
                ('time_delivery_car_on_borehole', models.CharField(blank=True, help_text='Время подачи на скважину', max_length=100, null=True, verbose_name='Время подачи на скважину')),
                ('quantity_hours', models.IntegerField(blank=True, help_text='Количество часов', null=True, verbose_name='Количество часов')),
                ('note', models.CharField(blank=True, help_text='Примечание', max_length=300, null=True, verbose_name='Примечание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время подачи заявки')),
                ('order_date', models.DateField(help_text='Укажите дату на которую заявляется транспорт', null=True, verbose_name='Дата заявки')),
                ('car', models.ForeignKey(blank=True, help_text='Транспортное средство', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.car', verbose_name='ТС')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
