# Generated by Django 3.2.16 on 2023-09-15 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(help_text='Цех/отдел/департамент', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.department', verbose_name='Цех/отдел/департамент'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_car',
            field=models.ForeignKey(help_text='Тип транспортного средства', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.typecar', verbose_name='Тип ТС'),
        ),
    ]
