# Generated by Django 3.2.16 on 2023-03-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_type'),
        ('orders', '0003_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='brand',
            field=models.ForeignKey(help_text='Марка транспортного средства', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_brand', to='cars.car', verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reg_mark',
            field=models.ForeignKey(help_text='Гос.рег.знак', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_mark', to='cars.car', verbose_name='ГРЗ'),
        ),
    ]
