# Generated by Django 3.2.16 on 2023-08-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20230831_1455'),
        ('orders', '0012_alter_application_time_delivery_car_on_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reg_mark',
        ),
        migrations.AddField(
            model_name='application',
            name='car',
            field=models.ForeignKey(blank=True, help_text='Транспортное средство', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.car', verbose_name='ТС'),
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Цех/отдел', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.department', verbose_name='Цех/отдел'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_car',
            field=models.ForeignKey(help_text='Тип транспортного средства', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='cars.typecar', verbose_name='Тип ТС'),
        ),
    ]
