# Generated by Django 3.2.16 on 2023-09-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('reg_mark', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('column', models.ForeignKey(default='=колонна не указана=', help_text='Автотранспортная колонна', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.column', verbose_name='Колонна')),
                ('type', models.ForeignKey(default='=тип не указан=', help_text='Тип транспортного средства', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.typecar', verbose_name='Тип')),
            ],
        ),
    ]
