# Generated by Django 3.2.16 on 2023-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('reg_mark', models.CharField(max_length=200)),
            ],
        ),
    ]
