# Generated by Django 3.2.16 on 2023-09-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='type_car',
        ),
    ]
