# Generated by Django 3.2.16 on 2023-01-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230112_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='title',
        ),
    ]
