# Generated by Django 3.2.16 on 2023-01-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_name_column_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='column',
            field=models.ForeignKey(blank=True, help_text='Автотранспортная колонна', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.column', verbose_name='Колонна'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип транспортного средства', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='cars.typecar', verbose_name='Тип'),
        ),
    ]
