# Generated by Django 3.2.16 on 2023-01-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230125_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='column',
            field=models.ForeignKey(help_text='Автотранспортная колонна', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.column', verbose_name='Колонна'),
        ),
    ]
