# Generated by Django 3.2.16 on 2023-02-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип транспортного средства', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.typecar', verbose_name='Тип'),
        ),
    ]
