# Generated by Django 3.2.16 on 2023-08-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typecar',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='column',
            field=models.ForeignKey(default='=колонна не указана=', help_text='Автотранспортная колонна', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.column', verbose_name='Колонна'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(default='=тип не указан=', help_text='Тип транспортного средства', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.typecar', verbose_name='Тип'),
        ),
    ]
