# Generated by Django 3.2.16 on 2023-02-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_type'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(help_text='Цех/отдел', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.department', verbose_name='Цех/отдел'),
        ),
        migrations.AddField(
            model_name='application',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_car',
            field=models.ForeignKey(help_text='Тип транспортного средства', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='cars.typecar', verbose_name='Тип ТС'),
        ),
    ]
