# Generated by Django 3.2.16 on 2023-03-16 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_alter_application_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Цех/отдел', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.department', verbose_name='Цех/отдел'),
        ),
    ]
