# Generated by Django 3.2.16 on 2023-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_time_delivery_car_on_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_delivery_car_on_base',
            field=models.CharField(blank=True, help_text='Время подачи на БПО', max_length=100, null=True, verbose_name='Время подачи на БПО'),
        ),
    ]
